config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "notes#home"
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = Note.all.order(updated_at: :desc)
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to @note, notice: 'Note was successfully created.'
    else
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to notes_path
  end

  private

  def note_params
    params.require(:note).permit(:title, :content, :tag)
  end

  def set_note
    @note = Note.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenNotesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/remixicon@4.1.0/fonts/remixicon.css" %>
  </head>

  <body>
    <main class="w-screen h-screen bg-primary">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: note, class: "max-w-md mx-auto" do |form| %>
  <div class="mb-4">
    <% note.errors.full_messages_for(:title).each do |message| %>
      <div class="text-red-500"><%= message %></div>
    <% end %>
  </div>
  <div class="mb-4">
    <div>
      <%= form.label :title, class: "block text-slate-100 font-bold mb-2" %>
      <%= form.text_field :title, class: "form-input mt-1 block w-full rounded-md", required: true %>
    </div>
  </div>
  <div class="mb-4">
    <div>
      <p class="text-slate-100 font-bold mb-2"><%= form.label :content %></p>
      <%= form.text_area :content, class: "form-textarea h-60 mt-1 block w-full rounded-md", required: true %>
    </div>
  </div>
  <div class="mb-4">
    <div>
      <p class="text-slate-100 font-bold mb-2"><%= form.label :tag %></p>
      <%= form.text_field :tag, class: "form-input mt-1 block w-full rounded-md", required: true %>
    </div>
  </div>
  <div class="mb-4">
    <%= form.submit "Submit", class: "button inline-flex gap-2 mb-auto mt-auto px-3 py-1 bg-slate-100 text-slate-900 rounded-lg" %> 
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class='w-full h-full flex flex-col justify-center items-center gap-4'>
  <div class="w-1/2 bg-purple-700 py-4 px-10 rounded-xl flex justify-between">
    <h1 class="inline-flex gap-2 text-2xl text-slate-100 font-bold"><i class="ri-file-edit-line"></i> Edit Note</h1>
    <%= link_to "<i class='ri-arrow-left-line'></i>Back to Gallery ".html_safe, notes_path, class: 'inline-flex gap-2 mb-auto mt-auto items-center h-full button px-3 py-1 bg-purple-700 text-slate-100 rounded-lg' %>
  </div>
  <div class="w-1/2 bg-purple-700 p-12 rounded-xl">
    <%= render "form", note: @note %>
  </div>
</div>

app/views/notes/home.html.erb
<div class="w-full h-full flex flex-col justify-center items-center">
  <div class="h-1/3 w-full bg-purple-700 flex flex-col justify-center items-center shadow-md rounded-b-xl">
    <h1 class="text-4xl text-slate-100 font-bold"><i class="ri-quill-pen-fill"></i>Open<span class="text-pink-400">Notes</span></h1>
    <p class="text-slate-100">A simple note-taking app made in <span class="underline underline-offset-4">Rails</span>, Styled with <span class="underline underline-offset-4">TailwindCSS</span></p>
  </div>
  <div class="bg-primary h-2/3 w-full flex flex-col justify-center items-center">
    <h1 class="text-4xl"><span class="font-bold">Write<span class="text-pink-400">Notes</span></span> now!</h1>
    <%= link_to "Continue to App <i class='ri-arrow-right-line'></i>".html_safe, notes_path, class: 'button px-3 py-1 bg-purple-700 text-slate-100 rounded-lg' %>
  </div>
</div>

app/views/notes/index.html.erb
<div class="page-container w-full h-full flex flex-col justify-start items-center ">
  <div class=" flex flex-row w-full justify-between align-center mb-12">
    <h1 class="text-4xl text-purple-700 font-bold"><i class="ri-quill-pen-fill"></i>My Notes</h1>
    <div class="flex flex-row gap-2">
      <%= link_to " New Note <i class='ri-add-fill'></i>".html_safe, new_note_path, class: 'inline-flex gap-2 mb-auto mt-auto button px-3 py-1 bg-purple-700 text-slate-100 rounded-lg' %>
    </div>
  </div>

  <div class="w-auto h-auto gap-8 overflow-scroll grid grid-cols-3">
    <% @notes.each do |note| %>
      <%= link_to note, class: "flex flex-col gap-2 w-80 card" do %>
        <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><%= note.title %></h1></div>
        <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg flex flex-col justify-between'><span><%= note.content.truncate(150, separator: '') %></span>
          <% if note.tag.present? %>
            <p class="font-light text-sm bg-slate-100 text-purple-700 w-fit px-3 py-1 rounded-lg"><%= note.tag %></p>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%# <div class="flex flex-col gap-2 w-80">
      <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><h1 class="font-bold text-xl text-center">hsdfhsdfhsdf</h1></div>
      <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg'><span>gfsdgdfsgsdf</span></div>
    </div>
    <div class="flex flex-col gap-2 w-80">
      <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><h1 class="font-bold text-xl text-center">hsdfhsdfhsdf</h1></div>
      <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg'><span>gfsdgdfsgsdf</span></div>
    </div>
    <div class="flex flex-col gap-2 w-80">
      <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><h1 class="font-bold text-xl text-center">hsdfhsdfhsdf</h1></div>
      <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg'><span>gfsdgdfsgsdf</span></div>
    </div>
    <div class="flex flex-col gap-2 w-80">
      <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><h1 class="font-bold text-xl text-center">hsdfhsdfhsdf</h1></div>
      <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg'><span>gfsdgdfsgsdf</span></div>
    </div>
    <div class="flex flex-col gap-2 w-80">
      <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><h1 class="font-bold text-xl text-center">hsdfhsdfhsdf</h1></div>
      <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg'><span>gfsdgdfsgsdf</span></div>
    </div>
    <div class="flex flex-col gap-2 w-80">
      <div class="p-3 bg-purple-700 text-slate-100 rounded-lg"><h1 class="font-bold text-xl text-center"><h1 class="font-bold text-xl text-center">hsdfhsdfhsdf</h1></div>
      <div class='h-40 container p-3 bg-purple-700 text-slate-100 rounded-lg'><span>gfsdgdfsgsdf</span></div>
    </div> %>
  </div>
    

  </div>
</div>

app/views/notes/new.html.erb
<div class='w-full h-full flex flex-col justify-center items-center gap-4'>
  <div class="w-1/2 bg-purple-700 py-4 px-10 rounded-xl flex justify-between">
    <h1 class="inline-flex gap-2 text-2xl text-slate-100 font-bold"><i class="ri-file-line"></i> New Note</h1>
    <%= link_to "<i class='ri-arrow-left-line'></i>Back to Gallery ".html_safe, notes_path, class: 'inline-flex gap-2 mb-auto mt-auto items-center h-full button px-3 py-1 bg-purple-700 text-slate-100 rounded-lg' %>
  </div>
  <div class="w-1/2 bg-purple-700 p-12 rounded-xl">
    <%= render "form", note: @note %>
  </div>
</div>

app/views/notes/show.html.erb
<div class="page-container w-full h-full flex flex-col justify-start items-start ">
  <div class=" flex flex-row w-full justify-between align-center mb-12">
    <h1 class="inline-flex gap-2 text-2xl text-purple-700 font-bold"><i class="ri-booklet-line"></i><%= @note.title %></h1>
    <div class="flex flex-row gap-2 justify-center items-center">
      <%= link_to "<i class='ri-arrow-left-line'></i>Back to Gallery ".html_safe, notes_path, class: 'inline-flex gap-2 mb-auto mt-auto button px-3 py-1 bg-purple-700 text-slate-100 rounded-lg' %>
      <%= link_to "<i class='ri-quill-pen-fill'></i>Edit This Note ".html_safe, edit_note_path(@note), class: 'inline-flex gap-2 mb-auto mt-auto button-white px-3 py-1 bg-slate-200 text-purple-700 rounded-lg' %>
      <%= button_to @note, :method => :delete, class: 'hover:bg-red-700 inline-flex justify-center items-center gap-2 button px-3 py-1 text-red-700 hover:text-slate-100 rounded-lg' do %>
        <i class="ri-delete-bin-6-line"></i> 
      <% end %>
    </div>
  </div>
  <div class="page-container h-full w-full bg-purple-700 bg-opacity-15 rounded-xl">
    <p class="font-medium text-justify"><%= @note.content %></p>
  </div>
</div>